apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webtool
  name: webtool
spec:
  containers:
    - image: httpd
      name: webtool
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}