apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kucc8
  name: kucc8
spec:
  containers:
    - image: nginx
      name: nginx-container
    - image: redis
      name: redis-container
    - image: memcached
      name: memcached-container