apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    run: busybox
spec:
  containers:
    - name: busybox-container1
      image: busybox
      args: ["/bin/sh", "-c", "ls; sleep 3600"]
      volumeMounts:
        - name: echolog
          mountPath: /var/log

    - name: busybox-container2
      image: busybox
      args: ["/bin/sh", "-c", "echo Hello World; sleep 3600"]
      volumeMounts:
        - name: echolog
          mountPath: /var/log

    - name: busybox-container3
      image: busybox
      args: ["/bin/sh", "-c", "echo this is the third container; sleep 3600"]
      volumeMounts:
        - name: echolog
          mountPath: /var/log

  volumes:
    - name: echolog
      emptyDir: {}

  restartPolicy: Always
