apiVersion: v1
kind: Pod
metadata:
  name: hungry-bear
  labels:
    app: myapp
spec:
  volumes:
    - name: workdir
      emptyDir: {}
  initContainers:
    - name: create
      image: alpine
      command: ['sh', '-c', 'touch /workdir/calm.txt']
      volumeMounts:
        - name: workdir
          mountPath: /workdir
  containers:
    - name: checker
      image: alpine
      command: ['sh', '-c', 'if [ -f /workdir/calm.txt ]; then echo "The app is running!"; sleep 3600; else echo "Missing calm.txt"; exit 1; fi']
      volumeMounts:
        - name: workdir
          mountPath: /workdir
