apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myapp
  name: myapp-pod
spec:
  initContainers:
    - name: init-myservice
      image: busybox:1.28
  containers:
    - image: busybox
      name: myapp-init-pod
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
