apiVersion: v1
kind: Pod
metadata:
  name: non-persistent-redis
  namespace: staging
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: cache-control
          mountPath: /data/redis
  volumes:
    - name: cache-control
      emptyDir: {}